#FROM bioconductor/bioconductor_docker:RELEASE_3_18

FROM rocker/r-ver:4.3.2
# 1.  run this to ensure the OS has what the R packages need
RUN apt-get update && apt-get install -y \
    libxml2-dev \
    libssl-dev \
    libcurl4-openssl-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# 2. Install BiocManager
RUN R -e "install.packages('BiocManager', repos='http://cran.rstudio.com/')"

# 3. Install R Packages via BiocManager (the "No-CRAN" preferred way)
# We include glue, jsonlite, and ShortRead in the BiocManager call
RUN R -e "BiocManager::install(c( \
    'dada2', \
    'ShortRead', \
    'glue', \
    'jsonlite' \
    ), ask=FALSE, Ncpus=4)"

# Prima COPIA il file dal tuo PC al container
COPY ./scripts/script_16s_dada2.r /usr/local/bin/dada2_pipeline.R
# Ora puoi cambiare i permessi, perché il file ESISTE
RUN chmod +x /usr/local/bin/dada2_pipeline.R
